# MINIMUM ANDROID VERSION ALLOWED
minimum_android_version_code: 5

question_types: 
        ['SELECT_ONE', 'SELECT_MULTIPLE', 'SELECT_ONE_WRITE_OTHER',
        'SELECT_MULTIPLE_WRITE_OTHER', 'FREE_RESPONSE', 'SLIDER', 'DATE', 
        'RATING', 'TIME', 'LIST_OF_TEXT_BOXES', 'INTEGER', 'EMAIL_ADDRESS',
        'DECIMAL_NUMBER', 'INSTRUCTIONS', 'MONTH_AND_YEAR', 'YEAR', 
        'PHONE_NUMBER', 'ADDRESS', 'REAR_PICTURE', 'FRONT_PICTURE',
        'SELECT_ONE_IMAGE', 'SELECT_MULTIPLE_IMAGE', 'LIST_OF_INTEGER_BOXES',
        'LABELED_SLIDER']

question_with_options: ['SELECT_ONE', 'SELECT_MULTIPLE', 'SELECT_ONE_WRITE_OTHER', 'SELECT_MULTIPLE_WRITE_OTHER', 'LIST_OF_TEXT_BOXES', 'LIST_OF_INTEGER_BOXES', 'LABELED_SLIDER']
question_with_images: ['SELECT_ONE_IMAGE', 'SELECT_MULTIPLE_IMAGE']
question_with_other: ['SELECT_ONE_WRITE_OTHER', 'SELECT_MULTIPLE_WRITE_OTHER']
question_with_select_multiple: ['SELECT_MULTIPLE', 'SELECT_MULTIPLE_WRITE_OTHER', 'SELECT_MULTIPLE_IMAGE']
question_with_multiple_skips: ['SELECT_ONE']

rule_types: 
  instrument_survey_limit_rule:
    constant_name: 'INSTRUMENT_SURVEY_LIMIT_RULE'
    pretty_name: 'Instrument Survey Limit Rule'
    params: ['max_surveys']
    description: 'Limit the number of surveys that can be created for an instrument per device.'
  instrument_timing_rule:
    constant_name: 'INSTRUMENT_TIMING_RULE'
    pretty_name: 'Instrument Timing Rule'
    params: ['start_time', 'end_time']
    description: 'Only make this instrument available during certain times of the day.'
  instrument_survey_limit_per_minute_rule:
    constant_name: 'INSTRUMENT_SURVEY_LIMIT_PER_MINUTE_RULE'
    pretty_name: 'Instrument Survey Limit Per Minute Rule'
    params: ['num_surveys', 'minute_interval']
    description: 'Limit the number of surveys that can be completed per time interval (specified in minutes).'
  instrument_launch_rule:
    constant_name: 'INSTRUMENT_LAUNCH_RULE'
    pretty_name: 'Instrument Launch Rule'
    params: []
    description: 'Setting this rule will make it so that a survey cannot be generated for an instrument from the app.  A survey must be launched from another app.'
  participant_type_rule:
    constant_name: 'PARTICIPANT_TYPE_RULE'
    pretty_name: 'Participant Type Rule'
    params: ['Child', 'Caregiver', 'Center']
    description: 'Limit an instrument such that it can only be created for a certain type of participant.'
 
# List delimiter for options
list_delimiter: ','

# Delimiter for items in option dictionary
dictionary_delimiter: ';'

# ISO 639-1 codes of supported languages
languages: [
             ['English', 'en'],
             ['Amharic', 'am'],
             ['Arabic', 'ar'],
             ['Khmer', 'km'],
             ['Spanish', 'es'],
             ['Swahili', 'sw'],
             ['Telugu', 'te']
          ]

# Special Responses
special_responses: ['SKIP', 'NA', 'RF', 'DK']

right_align_languages: ['ar']

exception_notifications:
  email_prefix: '[RailsSurvey] '
  sender: 'noreply@chpir.org'
  recipients: ['michael@chpir.org', 'leonard@chpir.org']

questions_per_page: 15
pages_to_show: 15
danger_zone_days: 3
